-- This is auto-generated code
SELECT
    TOP 100 *
FROM
    OPENROWSET(
        BULK 'https://supplychainanalyticsazu.dfs.core.windows.net/supplychainanalytics/Transformed-data/supplychaindataset/part-00000-tid-8641796433040205747-aef62e2d-ef8a-4bb1-ba42-a3a09a124965-8-1-c000.csv',
        FORMAT = 'CSV',
        PARSER_VERSION = '2.0',
        HEADER_ROW = TRUE
    ) AS [result]


-- Total revenue generated by each product type
SELECT 
    "Product type", 
    SUM("Revenue generated") AS total_revenue
FROM  OPENROWSET(
        BULK 'https://supplychainanalyticsazu.dfs.core.windows.net/supplychainanalytics/Transformed-data/supplychaindataset/part-00000-tid-8641796433040205747-aef62e2d-ef8a-4bb1-ba42-a3a09a124965-8-1-c000.csv',
        FORMAT = 'CSV',
        PARSER_VERSION = '2.0',
        HEADER_ROW = TRUE
    ) AS [result]
GROUP BY "Product type";


-- Top 5 SKUs with the highest profit
SELECT 
    [SKU], 
    [Profit]
FROM 
    OPENROWSET(
        BULK 'https://supplychainanalyticsazu.dfs.core.windows.net/supplychainanalytics/Transformed-data/supplychaindataset/part-00000-tid-8641796433040205747-aef62e2d-ef8a-4bb1-ba42-a3a09a124965-8-1-c000.csv',
        FORMAT = 'CSV',
        PARSER_VERSION = '2.0',
        HEADER_ROW = TRUE
    ) AS [result]
ORDER BY [Profit] DESC
OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;

-- Count of products sold based on customer demographics
SELECT 
    [Customer demographics], 
    SUM([Number of products sold]) AS total_sold
FROM 
    OPENROWSET(
        BULK 'https://supplychainanalyticsazu.dfs.core.windows.net/supplychainanalytics/Transformed-data/supplychaindataset/part-00000-tid-8641796433040205747-aef62e2d-ef8a-4bb1-ba42-a3a09a124965-8-1-c000.csv',
        FORMAT = 'CSV',
        PARSER_VERSION = '2.0',
        HEADER_ROW = TRUE
    ) AS [result]
GROUP BY [Customer demographics];

--Average lead time for different transportation modes
SELECT 
    [Transportation modes], 
    AVG([Lead time]) AS average_lead_time
FROM 
    OPENROWSET(
        BULK 'https://supplychainanalyticsazu.dfs.core.windows.net/supplychainanalytics/Transformed-data/supplychaindataset/part-00000-tid-8641796433040205747-aef62e2d-ef8a-4bb1-ba42-a3a09a124965-8-1-c000.csv',
        FORMAT = 'CSV',
        PARSER_VERSION = '2.0',
        HEADER_ROW = TRUE
    ) AS [result]
GROUP BY [Transportation modes];

-- Total manufacturing costs per route
SELECT 
    [Routes], 
    SUM([Manufacturing costs]) AS total_cost
FROM 
    OPENROWSET(
        BULK 'https://supplychainanalyticsazu.dfs.core.windows.net/supplychainanalytics/Transformed-data/supplychaindataset/part-00000-tid-8641796433040205747-aef62e2d-ef8a-4bb1-ba42-a3a09a124965-8-1-c000.csv',
        FORMAT = 'CSV',
        PARSER_VERSION = '2.0',
        HEADER_ROW = TRUE
    ) AS [result]
GROUP BY [Routes];

-- Find the product type with the highest defect rate

SELECT 
    [Product type], 
    MAX([Defect rates]) AS highest_defect_rate
FROM 
    OPENROWSET(
        BULK 'https://supplychainanalyticsazu.dfs.core.windows.net/supplychainanalytics/Transformed-data/supplychaindataset/part-00000-tid-8641796433040205747-aef62e2d-ef8a-4bb1-ba42-a3a09a124965-8-1-c000.csv',
        FORMAT = 'CSV',
        PARSER_VERSION = '2.0',
        HEADER_ROW = TRUE
    ) AS [result]
GROUP BY [Product type];

-- Top 3 SKUs with the lowest stock levels
SELECT 
    [SKU], 
    [Stock levels]
FROM 
    OPENROWSET(
        BULK 'https://supplychainanalyticsazu.dfs.core.windows.net/supplychainanalytics/Transformed-data/supplychaindataset/part-00000-tid-8641796433040205747-aef62e2d-ef8a-4bb1-ba42-a3a09a124965-8-1-c000.csv',
        FORMAT = 'CSV',
        PARSER_VERSION = '2.0',
        HEADER_ROW = TRUE
    ) AS [result]
ORDER BY [Stock levels] ASC
OFFSET 0 ROWS FETCH NEXT 3 ROWS ONLY;

--Calculate the profit margin for each SKU

SELECT 
    [SKU], 
    ([Profit] - [Costs]) / [Costs] * 100 AS profit_margin
FROM 
    OPENROWSET(
        BULK 'https://supplychainanalyticsazu.dfs.core.windows.net/supplychainanalytics/Transformed-data/supplychaindataset/part-00000-tid-8641796433040205747-aef62e2d-ef8a-4bb1-ba42-a3a09a124965-8-1-c000.csv',
        FORMAT = 'CSV',
        PARSER_VERSION = '2.0',
        HEADER_ROW = TRUE
    ) AS [result];

-- Average manufacturing cost for products with 'Pending' inspection results

SELECT 
    AVG([Manufacturing costs]) AS average_cost
FROM 
    OPENROWSET(
        BULK 'https://supplychainanalyticsazu.dfs.core.windows.net/supplychainanalytics/Transformed-data/supplychaindataset/part-00000-tid-8641796433040205747-aef62e2d-ef8a-4bb1-ba42-a3a09a124965-8-1-c000.csv',
        FORMAT = 'CSV',
        PARSER_VERSION = '2.0',
        HEADER_ROW = TRUE
    ) AS [result]
WHERE [Inspection results] = 'Pending';


-- Average manufacturing cost for products with 'Pass' inspection results
SELECT 
    AVG([Manufacturing costs]) AS average_cost
FROM 
    OPENROWSET(
        BULK 'https://supplychainanalyticsazu.dfs.core.windows.net/supplychainanalytics/Transformed-data/supplychaindataset/part-00000-tid-8641796433040205747-aef62e2d-ef8a-4bb1-ba42-a3a09a124965-8-1-c000.csv',
        FORMAT = 'CSV',
        PARSER_VERSION = '2.0',
        HEADER_ROW = TRUE
    ) AS [result]
WHERE [Inspection results] = 'Pass';









